version: "3.8"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cargo_backend
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=cargo_db
      - AUTH_DB_HOST=auth_db
      - AUTH_DB_PORT=5432
      - AUTH_DB_USERNAME=postgres
      - AUTH_DB_PASSWORD=postgres
      - AUTH_DB_NAME=auth_db
      - APP_ENV=dev
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - JWT_EXPIRES_IN=15m
      - REFRESH_TOKEN_EXPIRES_IN=7d
    depends_on:
      db:
        condition: service_healthy
      auth_db:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/inquiries"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cargo_frontend
    environment:
      - VITE_BACKEND_URL=http://localhost:3000
      - VITE_AUTH_URL=http://localhost:3000/auth
      - HOST=0.0.0.0
      - PORT=5173
    ports:
      - "5173:5173"
    depends_on:
      api:
        condition: service_healthy
    networks:
      - my_network
    stdin_open: true
    tty: true

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cargo_db
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - my_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  auth_db:
    image: postgres:15-alpine
    container_name: auth_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5434:5432"
    volumes:
      - auth_pg_data:/var/lib/postgresql/data
    networks:
      - my_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  my_network:
    driver: bridge

volumes:
  pg_data:
  auth_pg_data:
