name: Build & Deploy Frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'

env:
  ECR_REPO: my-cargo-frontend            # name of the ECR repo
  IMAGE_TAG: ${{ github.sha }}           # commit SHA

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ---------- AWS credentials ----------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      # ---------- ECR login ----------
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # ---------- Build & push ----------
      - name: Build and push Docker image
        run: |
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/$ECR_REPO
          
          docker build -t $IMAGE_URI:$IMAGE_TAG frontend
          docker tag  $IMAGE_URI:$IMAGE_TAG $IMAGE_URI:latest
          
          docker push $IMAGE_URI:$IMAGE_TAG
          docker push $IMAGE_URI:latest

      # ---------- Deploy on EC2 ----------
      - name: Deploy on EC2 host
        uses: appleboy/ssh-action@v1
        with:
          host:     ${{ secrets.EC2_HOST }}
          username: ec2-user                 # or ubuntu
          key:      ${{ secrets.EC2_SSH_KEY }}
          script: |
            IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/$ECR_REPO
            docker pull $IMAGE_URI:$IMAGE_TAG
            docker pull $IMAGE_URI:latest
            docker-compose -f /docker-compose.yml up -d frontend
